package tabelagui_a3;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class JFrameTabelaA3 extends javax.swing.JFrame {

    /**
     * Creates new form JFrameTabelaA3
     */
    public JFrameTabelaA3() {
        initComponents();
        DefaultTableModel modelA = (DefaultTableModel) TabelaAlunos.getModel();
        TabelaAlunos.setRowSorter(new TableRowSorter(modelA));

        readJTable();
    }

    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) TabelaAlunos.getModel();
        modelo.setNumRows(0);
        AlunoDAO pdao = new AlunoDAO();

        for (AlunosTabela p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getNome(),
                p.getNota_a1(),
                p.getNota_a2(),
                p.getNota_a3()

            });

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        JBotaoSair = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TxtAluno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtNotaA2 = new javax.swing.JTextField();
        TxtNotaA3 = new javax.swing.JTextField();
        BotãoCadastro = new javax.swing.JButton();
        TxtNotaA1 = new javax.swing.JTextField();
        BotãoExcluir = new javax.swing.JButton();
        BotãoAtualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaAlunos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaTeste = new javax.swing.JTable();
        TesteImprimir = new javax.swing.JButton();
        TesteExcluir = new javax.swing.JButton();
        TesteAlunoTxt = new javax.swing.JTextField();
        TesteNotaA1Txt = new javax.swing.JTextField();
        TesteNotaA2Txt = new javax.swing.JTextField();
        TesteNotaA3Txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EDUCONTROL");

        JBotaoSair.setBackground(new java.awt.Color(0, 51, 51));
        JBotaoSair.setForeground(new java.awt.Color(255, 255, 255));
        JBotaoSair.setText("Sair");
        JBotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBotaoSairActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ver Faltas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBotaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBotaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        TxtAluno.setBackground(new java.awt.Color(0, 51, 51));
        TxtAluno.setForeground(new java.awt.Color(255, 255, 255));
        TxtAluno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtAlunoActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Aluno");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nota A1");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nota A2");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nota A3");

        TxtNotaA2.setBackground(new java.awt.Color(0, 51, 51));
        TxtNotaA2.setForeground(new java.awt.Color(255, 255, 255));
        TxtNotaA2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtNotaA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNotaA2ActionPerformed(evt);
            }
        });

        TxtNotaA3.setBackground(new java.awt.Color(0, 51, 51));
        TxtNotaA3.setForeground(new java.awt.Color(255, 255, 255));
        TxtNotaA3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtNotaA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNotaA3ActionPerformed(evt);
            }
        });

        BotãoCadastro.setBackground(new java.awt.Color(0, 51, 51));
        BotãoCadastro.setForeground(new java.awt.Color(255, 255, 255));
        BotãoCadastro.setText("Cadastrar Aluno");
        BotãoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoCadastroActionPerformed(evt);
            }
        });

        TxtNotaA1.setBackground(new java.awt.Color(0, 51, 51));
        TxtNotaA1.setForeground(new java.awt.Color(255, 255, 255));
        TxtNotaA1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtNotaA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNotaA1ActionPerformed(evt);
            }
        });

        BotãoExcluir.setBackground(new java.awt.Color(153, 0, 0));
        BotãoExcluir.setForeground(new java.awt.Color(255, 255, 255));
        BotãoExcluir.setText("Excluir Aluno");
        BotãoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoExcluirActionPerformed(evt);
            }
        });

        BotãoAtualizar.setBackground(new java.awt.Color(0, 102, 102));
        BotãoAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        BotãoAtualizar.setText("Atualizar cadastro");
        BotãoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotãoAtualizarActionPerformed(evt);
            }
        });

        TabelaAlunos.setBackground(new java.awt.Color(255, 255, 255));
        TabelaAlunos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TabelaAlunos.setForeground(new java.awt.Color(0, 0, 0));
        TabelaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Aluno", "Nota A1", "Nota A2", "Nota A3"
            }
        ));
        TabelaAlunos.setPreferredSize(new java.awt.Dimension(375, 0));
        TabelaAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaAlunosMouseClicked(evt);
            }
        });
        TabelaAlunos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TabelaAlunosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TabelaAlunosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaAlunos);

        TabelaTeste.setBackground(new java.awt.Color(255, 255, 255));
        TabelaTeste.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TabelaTeste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomes", "Nota.a1", "Nota.a2", "Nota.a3"
            }
        ));
        jScrollPane2.setViewportView(TabelaTeste);

        TesteImprimir.setBackground(new java.awt.Color(0, 102, 102));
        TesteImprimir.setForeground(new java.awt.Color(255, 255, 255));
        TesteImprimir.setText("Imprimir cadastro");
        TesteImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TesteImprimirActionPerformed(evt);
            }
        });

        TesteExcluir.setBackground(new java.awt.Color(102, 0, 0));
        TesteExcluir.setForeground(new java.awt.Color(255, 255, 255));
        TesteExcluir.setText("Excluir cadastro");
        TesteExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TesteExcluirActionPerformed(evt);
            }
        });

        TesteAlunoTxt.setBackground(new java.awt.Color(0, 102, 102));
        TesteAlunoTxt.setForeground(new java.awt.Color(255, 255, 255));
        TesteAlunoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TesteAlunoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TesteAlunoTxtActionPerformed(evt);
            }
        });

        TesteNotaA1Txt.setBackground(new java.awt.Color(0, 102, 102));
        TesteNotaA1Txt.setForeground(new java.awt.Color(255, 255, 255));
        TesteNotaA1Txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TesteNotaA1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TesteNotaA1TxtActionPerformed(evt);
            }
        });

        TesteNotaA2Txt.setBackground(new java.awt.Color(0, 102, 102));
        TesteNotaA2Txt.setForeground(new java.awt.Color(255, 255, 255));
        TesteNotaA2Txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TesteNotaA3Txt.setBackground(new java.awt.Color(0, 102, 102));
        TesteNotaA3Txt.setForeground(new java.awt.Color(255, 255, 255));
        TesteNotaA3Txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TesteNotaA3Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TesteNotaA3TxtActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Aluno");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nota a1");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nota a2");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nota a3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(BotãoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BotãoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(BotãoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(243, 243, 243))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TxtAluno)
                                        .addComponent(jLabel1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TxtNotaA1)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TxtNotaA2)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(TxtNotaA3))
                                    .addGap(49, 49, 49)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(TesteImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(34, 34, 34)
                                    .addComponent(TesteExcluir)
                                    .addGap(19, 19, 19))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TesteAlunoTxt)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TesteNotaA1Txt)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TesteNotaA2Txt)
                                        .addComponent(jLabel8))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TesteNotaA3Txt)
                                        .addComponent(jLabel9))
                                    .addContainerGap()))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(738, 738, 738))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(BotãoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotãoExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtAluno)
                    .addComponent(TxtNotaA2)
                    .addComponent(TxtNotaA3)
                    .addComponent(TxtNotaA1)
                    .addComponent(TesteAlunoTxt)
                    .addComponent(TesteNotaA1Txt)
                    .addComponent(TesteNotaA2Txt)
                    .addComponent(TesteNotaA3Txt))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotãoCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TesteImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TesteExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtAlunoActionPerformed

    private void TxtNotaA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNotaA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNotaA2ActionPerformed

    private void TxtNotaA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNotaA3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNotaA3ActionPerformed

    private void BotãoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoCadastroActionPerformed

        AlunosTabela p = new AlunosTabela();
        AlunoDAO dao = new AlunoDAO();
        p.setNome(TxtAluno.getText());
        p.setNota_a1(Integer.parseInt(TxtNotaA1.getText()));
        p.setNota_a2(Integer.parseInt(TxtNotaA2.getText()));
        p.setNota_a3(Integer.parseInt(TxtNotaA3.getText()));
        dao.create(p);

        TxtAluno.setText("");
        TxtNotaA1.setText("");
        TxtNotaA2.setText("");
        TxtNotaA3.setText("");

        readJTable();

      DefaultTableModel CadastrarAluno = (DefaultTableModel) TabelaAlunos.getModel();  
      Object[] dados = {TxtAluno.getText(),TxtNotaA1.getText(),TxtNotaA2.getText(),TxtNotaA3.getText()};
      CadastrarAluno.addRow(dados);
    }//GEN-LAST:event_BotãoCadastroActionPerformed

    private void TxtNotaA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNotaA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNotaA1ActionPerformed

    private void BotãoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoExcluirActionPerformed
        if (TabelaAlunos.getSelectedRow() != -1) {

            Object[] opcoes = {"Sim", "Não"};

            int resposta = JOptionPane.showOptionDialog(
                    null, "Tem certeza que quer excluir?", "Confirmação",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    opcoes, opcoes[1]
            );

            if (resposta == JOptionPane.YES_OPTION) {
                AlunosTabela p = new AlunosTabela();
            AlunoDAO dao = new AlunoDAO();          
            p.setId((int)TabelaAlunos.getValueAt(TabelaAlunos.getSelectedRow(), 0));
            dao.delete(p);

            TxtAluno.setText("");
            TxtNotaA1.setText("");
            TxtNotaA2.setText("");
            TxtNotaA3.setText("");

            readJTable();            
                                                
            } else {
                JOptionPane.showMessageDialog(null, "Exclusão cancelada.");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um aluno para excluir.");
        }
    }//GEN-LAST:event_BotãoExcluirActionPerformed

    private void BotãoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotãoAtualizarActionPerformed
        if (TabelaAlunos.getSelectedRow() != -1) {

            AlunosTabela p = new AlunosTabela();
            AlunoDAO dao = new AlunoDAO();
            p.setNome(TxtAluno.getText());
            p.setNota_a1(Integer.parseInt(TxtNotaA1.getText()));
            p.setNota_a2(Integer.parseInt(TxtNotaA2.getText()));
            p.setNota_a3(Integer.parseInt(TxtNotaA3.getText()));
            p.setId((int)TabelaAlunos.getValueAt(TabelaAlunos.getSelectedRow(), 0));
            dao.update(p);

            TxtAluno.setText("");
            TxtNotaA1.setText("");
            TxtNotaA2.setText("");
            TxtNotaA3.setText("");

            readJTable();

//         TabelaAlunos.setValueAt(TxtAluno.getText(), TabelaAlunos.getSelectedRow(), 0);
//         TabelaAlunos.setValueAt(TxtNotaA1.getText(), TabelaAlunos.getSelectedRow(), 1);
//         TabelaAlunos.setValueAt(TxtNotaA2.getText(), TabelaAlunos.getSelectedRow(), 2);
//         TabelaAlunos.setValueAt(TxtNotaA3.getText(), TabelaAlunos.getSelectedRow(), 3);
        }
    }//GEN-LAST:event_BotãoAtualizarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CalendarioFaltas calendario = new CalendarioFaltas();
        calendario.setVisible(true);
        calendario.pack();
        calendario.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TabelaAlunosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaAlunosKeyReleased
        if (TabelaAlunos.getSelectedRow() != -1) {

            TxtAluno.setText(TabelaAlunos.getValueAt(TabelaAlunos.getSelectedRow(), 1).toString());
            TxtNotaA1.setText(TabelaAlunos.getValueAt(TabelaAlunos.getSelectedRow(), 2).toString());
            TxtNotaA2.setText(TabelaAlunos.getValueAt(TabelaAlunos.getSelectedRow(), 3).toString());
            TxtNotaA3.setText(TabelaAlunos.getValueAt(TabelaAlunos.getSelectedRow(), 4).toString());

        }
    }//GEN-LAST:event_TabelaAlunosKeyReleased

    private void TabelaAlunosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TabelaAlunosKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelaAlunosKeyPressed

    private void TabelaAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaAlunosMouseClicked
        if (TabelaAlunos.getSelectedRow() != -1) {

            TxtAluno.setText(TabelaAlunos.getValueAt(TabelaAlunos.getSelectedRow(), 1).toString());
            TxtNotaA1.setText(TabelaAlunos.getValueAt(TabelaAlunos.getSelectedRow(), 2).toString());
            TxtNotaA2.setText(TabelaAlunos.getValueAt(TabelaAlunos.getSelectedRow(), 3).toString());
            TxtNotaA3.setText(TabelaAlunos.getValueAt(TabelaAlunos.getSelectedRow(), 4).toString());

        }
    }//GEN-LAST:event_TabelaAlunosMouseClicked

    private void TesteAlunoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TesteAlunoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TesteAlunoTxtActionPerformed

    private void TesteNotaA1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TesteNotaA1TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TesteNotaA1TxtActionPerformed

    private void TesteNotaA3TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TesteNotaA3TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TesteNotaA3TxtActionPerformed

    private void TesteImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TesteImprimirActionPerformed
        DefaultTableModel dtmAlunos = (DefaultTableModel) TabelaTeste.getModel();
        Object[] info = {TesteAlunoTxt.getText(),TesteNotaA1Txt.getText(),TesteNotaA2Txt.getText(),TesteNotaA3Txt.getText()};
        dtmAlunos.addRow(info);
    }//GEN-LAST:event_TesteImprimirActionPerformed

    private void TesteExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TesteExcluirActionPerformed
        if (TabelaTeste.getSelectedRow() != -1) {
    Object[] opcoes = {"Sim", "Não"};

    int resposta = JOptionPane.showOptionDialog(
            null, 
            "Tem certeza que quer excluir?", 
            "Confirmação",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            opcoes, 
            opcoes[1]
    );

    if (resposta == JOptionPane.YES_OPTION) {
        DefaultTableModel dtmAlunos = (DefaultTableModel) TabelaTeste.getModel();
        dtmAlunos.removeRow(TabelaTeste.getSelectedRow());
    } else {
        JOptionPane.showMessageDialog(null, "Exclusão cancelada.");
    }
} else {
    JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
}
    }//GEN-LAST:event_TesteExcluirActionPerformed

    private void JBotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBotaoSairActionPerformed
        int resposta = JOptionPane.showConfirmDialog(
        this,
        "Tem certeza que deseja deslogar?",
        "Confirmação",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );

    if (resposta == JOptionPane.YES_OPTION) {
        this.dispose();
        
        Login login = new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null); 
    } 
    }//GEN-LAST:event_JBotaoSairActionPerformed

    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotãoAtualizar;
    private javax.swing.JButton BotãoCadastro;
    private javax.swing.JButton BotãoExcluir;
    private javax.swing.JButton JBotaoSair;
    private javax.swing.JTable TabelaAlunos;
    private javax.swing.JTable TabelaTeste;
    private javax.swing.JTextField TesteAlunoTxt;
    private javax.swing.JButton TesteExcluir;
    private javax.swing.JButton TesteImprimir;
    private javax.swing.JTextField TesteNotaA1Txt;
    private javax.swing.JTextField TesteNotaA2Txt;
    private javax.swing.JTextField TesteNotaA3Txt;
    private javax.swing.JTextField TxtAluno;
    private javax.swing.JTextField TxtNotaA1;
    private javax.swing.JTextField TxtNotaA2;
    private javax.swing.JTextField TxtNotaA3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
